### ISSUE TITLE
Colab please?

### ISSUE THREAD

**Issue by Tylersuard** [PeihaoChen/regnet#1]
First of all, thank you for creating this.  I was looking for an implementation of that paper.  Second, I'm having a lot of problems installing this.  I am sure you are very busy, but could you create an easy Google Colab notebook so I can run this?
Thank you.

**Comment by PeihaoChen** [comment]
Thank you for your interest and suggestion. However, Colab may not be available in the coming days. If you have any questions when you run the codes, please submit an issue and I will fix it as soon as possible.

**Comment by Tylersuard** [comment]
Ok, thank you. The issue is not with your code, it’s that some of the dependencies are not available when I try to install them. I will try again later, thank you for your response.
