### ISSUE TITLE
Pretrained models

### ISSUE THREAD

**Issue by pietrobolcato** [PeihaoChen/regnet#2]
Hello! First of all thank you for the great work, is incredible! 🥇 

Would it be possible for you to share the pretrained RegNet models? 

Thank you in advance! :)

**Comment by PeihaoChen** [comment]
> Hello! First of all thank you for the great work, is incredible! 🥇
> 
> Would it be possible for you to share the pretrained RegNet models?
> 
> Thank you in advance! :)

Thank you for your interest. We will release the pre-trained RegNet in the next week. Enjoy your experiments.

**Comment by pietrobolcato** [comment]
That's wonderful, thank you! And also congrats not only for the research but for making it accessible to everybody by opensourcing code and models 🥇

**Comment by blingopen** [comment]
Hello, would you mind sharing your pre-trained models again? Your shared link has been unavailable. Thank you in advance!
