### ISSUE TITLE
Can we replace WaveNet with STFT Reconstruction + Griffin Lim?

### ISSUE THREAD

**Issue by v-iashin** [PeihaoChen/regnet#3]
Hi,

First of all, thanks for sharing the code and instructions on how to run it!

I was wondering since WaveNet inference takes ~30mins per sample would it be possible to replace it with Inverse Mel Spec (STFT reconstruction) + Griffin Lim reconstruction?

I tried to do it but it produces some unnatural robotic sound. Did you face the same problem?

Here is a Colab to play with (or check?) if you like
https://colab.research.google.com/drive/1kAk2StURLCefoxdIHtjYD92kHcXbNjn2?usp=sharing

and the file which I got after running the inference code
[video_02657.npy.zip](https://github.com/PeihaoChen/regnet/files/5710616/video_02657.npy.zip)

this is the audio produced after STFT and Griffin Lim instead of WaveNet
[video_02657.wav.zip](https://github.com/PeihaoChen/regnet/files/5763435/video_02657.wav.zip)

**Comment by PeihaoChen** [comment]
Hi,

First, it is reasonable to replace WaveNet with Griffin Lim reconstruction. I remember that I have tried it before. The sound quality is quite good and it significantly speeds up the reconstruction process. However, I cannot find the relevant code now.

I guess there are somehitngs wrong in the paremeter settings when performing STFT and iSTFT. One tip for debugging is that you cound take a natural sound to perform STFT and iSTFT, ensuring that the genrated wavefrom is close to the original natural sound. Then, you use the spectrogram generated in this setting to train the RegNet. In this way, the predicted spectrogram should be able to reconstuct the waveform using iSTFT with your settings.

I hope the tip is helpful for you.

**Comment by v-iashin** [comment]
Hi Peihao,

Thanks for your suggestion. 

I looked into the implementation more carefully and noticed that you are using the energy spectrum (`power = 1`) when creating a mel-spectrogram
https://github.com/PeihaoChen/regnet/blob/199609e3a551918b82ca91ae8f0ffc8005f76e18/extract_mel_spectrogram.py#L19

Seems interesting. Is there any benefit which you might recall behind this approach compared to the more popular one, ie power spectrogram (`power = 2`)?

It also seems to be the root cause of the robotic sound after reconstruction (wave-mel-wave).  I tried with both powers and with/without pre-processing and in both cases with `power=2` it reconstructs much better sound: "robotic" sound is hardly noticeable if no preprocessing is done but more prominent if with preprocessing (which is ok since preprocessing is not suitable for squared values) 🙂 . 

Here I composed another colab for you to look into it if you are interested:
https://colab.research.google.com/drive/1ELnjVUlNTiaCbVEmt0U8Vw-TSyJU12-q?usp=sharing

The original audio, the one extracted with `extract_audio_and_video.py` (a bit loud):
[audio.wav.zip](https://github.com/PeihaoChen/regnet/files/5775001/audio.wav.zip)

Here is the code if you cannot access colab for any reason:
```python
! pip install librosa==0.7

## HERE I READ THE AUDIO AND GENERATE MELSPEC USING THE SAME FUNCTION (get_spectrogram())
import numpy as np
import librosa

mel_basis = librosa.filters.mel(
    22050,
    n_fft=1024,
    fmin=125, 
    fmax=7600, 
    n_mels=80
)

wav, _ = librosa.load('audio.wav', sr=None)
length = 10 * 22050
y = np.zeros(length)

if wav.shape[0] < length:
    y[:len(wav)] = wav
else:
    y = wav[:length]
    
# switch between these two:
spectrogram = np.abs(librosa.stft(y, n_fft=1024, hop_length=256))
# spectrogram = np.abs(librosa.stft(y, n_fft=1024, hop_length=256)) ** 2

mel_spec = np.dot(mel_basis, spectrogram)

mel_spec = np.maximum(1e-5, mel_spec)
print(mel_spec.min(), mel_spec.max(), (mel_spec == 1e-5).sum(), mel_spec.shape)
mel_spec = 20 * np.log10(mel_spec) - 20
mel_spec = (mel_spec + 100) / 100
mel_spec = np.clip(mel_spec, 0, 1.0)
print(mel_spec.min(), mel_spec.max(), (mel_spec == 0).sum(), (mel_spec == 1).sum(), mel_spec.shape)

mel_spec = mel_spec[:, :860]
np.save("audio_mel.npy", mel_spec)
np.save("audio_padded.npy", y)

## HERE I AM READING MELSPEC FROM THE DISK AND TRY TO RECONSTRUCT THE AUDIO
import librosa
from librosa.feature import inverse
import numpy as np

mel_spec = np.load('audio_mel.npy')
print(mel_spec.shape)

# Inversing the preprocessing from get_spectrogram
mel_spec *= 100
mel_spec -= 100
mel_spec += 20
mel_spec /= 20
mel_spec = 10 ** mel_spec

# spec = librosa.feature.inverse.mel_to_stft(
#     mel_spec, 
#     sr=22050,
#     n_fft=1024,
#     fmin=125, 
#     fmax=7600, 
# )
# print(spec.shape)

# audio = librosa.griffinlim(
#     spec,
#     hop_length=1024//4
# )

# the same as two above
audio = librosa.feature.inverse.mel_to_audio(
    mel_spec,
    sr=22050,
    n_fft=1024,
    hop_length=1024//4,
    fmin=125, 
    fmax=7600, 
)

print(audio.shape)
librosa.output.write_wav('audio_rec.wav', audio, 22050)
```

**Comment by v-iashin** [comment]
Oh sorry, my bad. `mel_to_audio` (because of `mel_to_stft`) is defaulting to `power=2` which means I was trying to reconstruct squared STFT values from non-squared mels. Hence, the robotic sound. 

I compared both again. They are hardly distinguishable from one another. Maybe squared values are slightly better but I don't think it is significant. 

Anyway, sorry for the false alarm.
