### ISSUE TITLE
Discrepancy between config file and arxiv paper

### ISSUE THREAD

**Issue by ChandraSekhar123331** [PeihaoChen/regnet#8]
The ArXiv paper says that the audio forwarding regularizer uses down-sampling + repeat operations. This corresponds to the `Auxiliary_lstm_sample` which is defined [here](https://github.com/PeihaoChen/regnet/blob/199609e3a551918b82ca91ae8f0ffc8005f76e18/model.py#L139). But both the [config.py](https://github.com/PeihaoChen/regnet/blob/199609e3a551918b82ca91ae8f0ffc8005f76e18/config.py) and [dog_opts.yml](https://github.com/PeihaoChen/regnet/blob/199609e3a551918b82ca91ae8f0ffc8005f76e18/config/dog_opts.yml) are using a different value(https://github.com/PeihaoChen/regnet/blob/199609e3a551918b82ca91ae8f0ffc8005f76e18/config.py#L35) which points to the function `Auxiliary_lstm_last` function which is defined [here](https://github.com/PeihaoChen/regnet/blob/199609e3a551918b82ca91ae8f0ffc8005f76e18/model.py#L122).

So is this a mistake or is the case that `Auxiliary_lstm_last` works better than `Auxiliary_lstm_sample`?

**Comment by PeihaoChen** [comment]
Hi, 

It not a mistake. Actually, `Auxiliary_lstm_last` is a special case of `Auxiliary_lstm_sample` (i.e., only sample the last features). In our implementation, we found that for some sound categories, only taking a small part of ground-truth audio (using `Auxiliary_lstm_last`)  is enough for representing the irrelevant sound. This is why we use `Auxiliary_lstm_last` for in some cases.

Enjoy coding!

**Comment by ChandraSekhar123331** [comment]
> Actually, Auxiliary_lstm_last is a special case of Auxiliary_lstm_sample (i.e., only sample the last features)

Ooh yes, I missed this. I understood it now.

Thanks!
